---
title: "Permutation tests for dFC Mode Metrics - META HCPEP RAW"
author: "Fran Hancock"
affiliation: Department of Neuroimaging, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK 
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: axtxtpt
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,load_libraries,echo=FALSE, message=FALSE,include=FALSE}


library(lmerTest)
library(coin)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(cowplot)
library(xlsx)
library(GGally)
library(knitr)
library(EnvStats)
library(rstatix)
library(MKinfer)
library(ARTool)

opts_knit$set(root.dir ='/Users/HDF/Dropbox/Fran/Academics/PhD/matlab/projects/HCPEP_COMPARE')

con_col<-"cornflowerblue"
pap_col<-"gold2"
nap_col<-"grey69"
colors<-c(con_col,nap_col)
etxt<-40
axtxt<-28
tittxt<-36
stittxt<-20
```

### Test assumptions for t-test and then run permutation t-tests

```{r,boxplots,echo=FALSE, message=FALSE}

Regtb1 <- read.csv('/Users/HDF/Dropbox/Fran/Academics/PhD/matlab/projects/HCPEP_CON/Regtable_MODES_RAW.csv',stringsAsFactors=TRUE)
Regtb2 <- read.csv('/Users/HDF/Dropbox/Fran/Academics/PhD/matlab/projects/HCPEP_NAP/Regtable_MODES_RAW.csv',stringsAsFactors=TRUE)

Regtb=rbind(Regtb1,Regtb2)

# define the mode colors 

mode1_col<-"grey69"
mode2_col<-"firebrick"
mode3_col<-"violet"
mode4_col<-"darkorange1"
mode5_col<-"purple"
```

### ANOVAS for META

```{r,anovas,echo=FALSE, message=FALSE}
# Test assumprions for 2 sample t-test


outliers<-Regtb %>%
  group_by(MODE) %>%
  identify_outliers("META")
# no extreme outliers

normality<-Regtb %>%
  group_by(MODE) %>%
  shapiro_test(META)
# p value > 0.5 for all modes so continue with 2 sample t-test

equil<-Regtb %>%
  group_by(MODE) %>%
  levene_test(META~COND)
# no diff in METAiance - no problem t-test META.equal = TRUE

effSize<-Regtb %>%
  group_by(MODE) %>% 
  cohens_d(META~COND,var.equal=TRUE)
# small to negligble effect size

write.xlsx(normality,"Results/03_Mode_META_PermAss.xlsx","normality")
write.xlsx(equil,"Results/03_Mode_META_PermAss.xlsx","equivalence", append=TRUE)
write.xlsx(effSize,"Results/03_Mode_META_PermAss.xlsx","effect size", append=TRUE)

# SO CANNOT USE t-test - need to use permutation

x<-Regtb[Regtb$COND %in% c("CON"),]
y<-Regtb[Regtb$COND %in% c("NAP"),]

mode<-c("MODE1","MODE2","MODE3","MODE4","MODE5")
mm<-1

# Correct here for multiple comparisons
cutpoints<-c(0, 0.0001/5, 0.001/5, 0.01/5, 0.05/5,  1)
  symbols<-c("****", "***", "**", "*",  "ns")
  
for( m in mode) {
  
  RegtbM<-Regtb[Regtb$MODE %in% c(m),]
  
  res.art<-art(META~COND*RUN + (1|SUB), data=RegtbM)
  res.aov<-anova(res.art)
  
  write.xlsx(res.aov,paste("Results/03_", m, "_META.xlsx",sep=""),"AOV")
  print("Results of 2x4 ANOVA")
  print(res.aov[3,5])
  
  if (res.aov[3,5] > 0.05){
    # there is no interaction so just run non-parametric 2-sample 
    print("No interaction - now just 2-sample test")
    
    pwc_cond <- RegtbM %>%
    wilcox_test(META ~ COND, paired=FALSE,p.adjust.method = "bonferroni") %>%
      add_significance()
    print(pwc_cond)
    
    effsize<-RegtbM %>%
      wilcox_effsize(META ~ COND)
    print(effsize)
    
    write.xlsx(pwc_cond,paste("Results/03_", m,"_META.xlsx",sep=""),"PWC_COND", append=TRUE)
    write.xlsx(effsize,paste("Results/03_",m,"_META.xlsx",sep=""),"Effect Size", append=TRUE)
    
  } else {
   # Interaction so just run 1-way anova for CON with Friednman test because it is a repeated measure 
    
    print("There was an interaction so run 1-sample for CON repeated measures - Friedmann")
    RegtbTmp<-RegtbM[RegtbM$COND %in% c("CON"),]
    
    res.fried<-friedman.test(data=RegtbTmp,META~RUN |SUB)
    print("Result of 1-way ANOVA for CON")
    print(res.fried)
    
    write.xlsx(sapply(res.fried,unlist),paste("Results/03_",m,"_META.xlsx",sep=""),"CON_FRIED", append=TRUE)
    print(res.fried$p.value)
    
    if (res.fried$p.value < 0.05){
      pwc_run <- RegtbTmp %>%
        wilcox_test(META ~ RUN, paired = TRUE, p.adjust.method = "bonferroni") %>%
        add_significance()
        effsize<-RegtbTmp %>%
          wilcox_effsize(META ~ RUN)
       
        write.xlsx(pwc_run,paste("Results/03_",m,"_META.xlsx",sep=""),"CON_PWC_RUN", append=TRUE)
        write.xlsx(effsize,paste("Results/03_",m,"_META.xlsx",sep=""),"CON Effect Size", append=TRUE)      
        print("Result of pwc for CON")
        print(pwc_run)
        print(effsize)
    }
    
    print("There was an interaction so run 1-sample for NAP repeated measures - Friedmann")
    RegtbTmp<-RegtbM[RegtbM$COND %in% c("NAP"),]
    
    res.fried<-friedman.test(data=RegtbTmp,META~RUN |SUB)
    print("Result of 1-way ANOVA for NAP")
    print(res.fried)
    write.xlsx(sapply(res.fried,unlist),paste("Results/03_",m,"_META.xlsx",sep=""),"NAP_FRIED", append=TRUE)
    res.fried$p.value
    
    if (res.fried$p.value < 0.05){
      pwc_run <- RegtbTmp %>%
        wilcox_test(META ~ RUN, paired = TRUE, p.adjust.method = "bonferroni") %>%
        add_significance()
        effsize<-RegtbTmp %>%
          wilcox_effsize(META ~ RUN)
        
        write.xlsx(pwc_run,paste("Results/03_",m,"_META.xlsx",sep=""),"NAP_PWC_RUN", append=TRUE)
        write.xlsx(effsize,paste("Results/03_",m,"_META.xlsx",sep=""),"NAP Effect Size", append=TRUE)   
        print("Result of pwc for NAP")
        print(pwc_run)
        print(effsize)
    }
    
    # run parametric 2-way for each RUN
   
    runs<-c('RUN1','RUN2','RUN3','RUN4')
    for(r in runs){
      Regtmp<-RegtbM[RegtbM$RUN %in% c(r),]
      
      pwc_cond <- Regtmp %>%
      wilcox_test(META~ COND, paired=FALSE,p.adjust.method = "bonferroni") %>%
        add_significance()
      effsize<-Regtmp %>%
          wilcox_effsize(META ~ COND)
      print(paste("Result for pwc for ", r))
      
     
      write.xlsx(pwc_cond,paste("Results/03_",m,"_META.xlsx",sep=""),paste(r,"_PWC_COND"), append=TRUE)
      write.xlsx(effsize,paste("Results/03_",m,"_META.xlsx",sep=""),paste(r,"_Effect Size"), append=TRUE) 
      
      print(pwc_cond)
      print(effsize)
    }
  }
} 
  
```
