---
title: "Permutation tests for dFC Mode Metrics - META HCPEP RAW"
author: "Fran Hancock"
affiliation: Department of Neuroimaging, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK 
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: axtxtpt
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,load_libraries,echo=FALSE, message=FALSE,include=FALSE}


library(lmerTest)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(cowplot)
library(xlsx)
library(GGally)
library(knitr)
library(EnvStats)
library(rstatix)
library(MKinfer)
library(PupillometryR)

# if (!require(remotes)) {
#     install.packages("remotes")
# }
# remotes::install_github('jorvlan/raincloudplots')
library(raincloudplots)
w_package = 3
h_package = 6

# packages <- c("ggplot2", "dplyr", "lavaan", "plyr", "cowplot", "rmarkdown", 
#               "readr", "caTools", "bitops")
# 
# if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
#   install.packages(setdiff(packages, rownames(installed.packages())))  
# }

opts_knit$set(root.dir ='/Users/HDF/Dropbox/Fran/Academics/PhD/matlab/projects/HCPEP_COMPARE')

con_col<-"cornflowerblue"
pap_col<-"gold2"
nap_col<-"grey69"
colors<-c(con_col,nap_col)
etxt<-40
axtxt<-28
tittxt<-36
stittxt<-20
```

### Test assumptions for t-test and then run permutation t-tests

```{r,boxplots,echo=FALSE, message=FALSE}

Regtb1 <- read.csv('/Users/HDF/Dropbox/Fran/Academics/PhD/matlab/projects/HCPEP_CON/Regtable_MODES_RAW.csv',stringsAsFactors=TRUE)
Regtb2 <- read.csv('/Users/HDF/Dropbox/Fran/Academics/PhD/matlab/projects/HCPEP_NAP/Regtable_MODES_RAW.csv',stringsAsFactors=TRUE)

Regtb=rbind(Regtb1,Regtb2)

# define the mode colors 

mode1_col<-"grey69"
mode2_col<-"firebrick"
mode3_col<-"violet"
mode4_col<-"darkorange1"
mode5_col<-"purple"
```

### rainclouds for META

```{r,meta,echo=FALSE, message=FALSE}
# Test assumprions for 2 sample t-test

run<-c("RUN1","RUN2","RUN3","RUN4")

for(r in run){
  RegtbR<-Regtb[Regtb$RUN %in% c(r),]

  bp <- ggplot(RegtbR, aes(x = MODE, y = META, fill = COND)) +
    geom_flat_violin(aes(fill = COND),position = position_nudge(x = .2, y = 0), adjust = 1, trim = FALSE, alpha = .5, colour = NA)+
    geom_point(aes(x = as.numeric(MODE)-.25, y = META, colour = COND),position = position_jitter(width = .05), size = 1, shape = 20)+
    geom_boxplot(aes(x = MODE, y = META, fill = COND),outlier.shape = NA, alpha = .5, width = .25, colour = "black")+
    scale_color_manual("COND", values=setNames(colors,levels(Regtb$COND)))+
    scale_fill_manual("COND", values=setNames(colors,levels(Regtb$COND)))+
    theme(plot.title = element_text(size=etxt, hjust = 0.5),
        axis.text = element_text(size = axtxt),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=tittxt),
        plot.subtitle = element_text(size=stittxt),
        plot.caption = element_text(size=stittxt),
        legend.text = element_text(size=stittxt),
        legend.title = element_blank()
        ) 
  if(r=="RUN1"){
    bp<-bp + 
      annotate(geom="text", x="MODE1",y=0.32, label="*",color="red",size=14)+
      annotate(geom="text", x="MODE5",y=0.32, label="****",color="red",size=14)
  }
  
  if(r=="RUN2"){
    bp<-bp + 
      annotate(geom="text", x="MODE1",y=0.32, label="*",color="red",size=14)
  }
  
  if(r=="RUN3"){
    bp<-bp + 
      annotate(geom="text", x="MODE1",y=0.32, label="*",color="red",size=14)+
      annotate(geom="text", x="MODE5",y=0.32, label="****",color="blue",size=14)
  }
  
  if(r=="RUN4"){
    bp<-bp + 
      annotate(geom="text", x="MODE1",y=0.32, label="*",color="red",size=14)+
      annotate(geom="text", x="MODE4",y=0.32, label="**",color="blue",size=14)
  }
  
 
  ggsave(paste("Figures/03_",r,"_META_CONNAP_mode_raincloud.pdf"), width=40, height=20, units="cm")
}        
```
### rainclouds for VAR

```{r,var,echo=FALSE, message=FALSE}
# Test assumprions for 2 sample t-test
for(r in run){
  RegtbR<-Regtb[Regtb$RUN %in% c(r),]
  
  bp <- ggplot(RegtbR, aes(x = MODE, y = VAR, fill = COND)) +
    geom_flat_violin(aes(fill = COND),position = position_nudge(x = .2, y = 0), adjust = 1, trim = FALSE, alpha = .5, colour = NA)+
    geom_point(aes(x = as.numeric(MODE)-.25, y = VAR, colour = COND),position = position_jitter(width = .05), size = 1, shape = 20)+
    geom_boxplot(aes(x = MODE, y = VAR, fill = COND),outlier.shape = NA, alpha = .5, width = .25, colour = "black")+
    scale_color_manual("COND", values=setNames(colors,levels(Regtb$COND)))+
    scale_fill_manual("COND", values=setNames(colors,levels(Regtb$COND)))+
    theme(plot.title = element_text(size=etxt, hjust = 0.5),
        axis.text = element_text(size = axtxt),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=tittxt),
        plot.subtitle = element_text(size=stittxt),
        plot.caption = element_text(size=stittxt),
        legend.text = element_text(size=stittxt),
        legend.title = element_blank()
        ) 
  if(r=="RUN1"){
    bp<-bp + 
      annotate(geom="text", x="MODE1",y=0.01, label="**",color="red",size=14)+
      annotate(geom="text", x="MODE2",y=0.01, label="**",color="red",size=14)+
      annotate(geom="text", x="MODE3",y=0.01, label="**",color="blue",size=14)+
      annotate(geom="text", x="MODE4",y=0.01, label="****",color="red",size=14)+
      annotate(geom="text", x="MODE5",y=0.01, label="**",color="red",size=14)
  }
  
  if(r=="RUN2"){
    bp<-bp + 
      annotate(geom="text", x="MODE1",y=0.01, label="***",color="red",size=14)+
      annotate(geom="text", x="MODE2",y=0.01, label="**",color="red",size=14)+
      annotate(geom="text", x="MODE4",y=0.01, label="****",color="red",size=14)+
      annotate(geom="text", x="MODE5",y=0.01, label="**",color="red",size=14)
  }
  
  if(r=="RUN3"){
    bp<-bp + 
      annotate(geom="text", x="MODE5",y=0.01, label="**",color="red",size=14)
  }
  if(r=="RUN4"){
    bp<-bp +
      annotate(geom="text", x="MODE5",y=0.01, label="**",color="red",size=14)
  }
  ggsave(paste("Figures/03_",r,"_VAR_CONNAP_mode_raincloud.pdf"), width=40, height=20, units="cm")
}
```
